name: Padel-court occupancy

on:
  schedule:
    # Summer (Irish time = UTC+1)
    - cron: '50 19 * * 6,0'   # 20:50 Sat/Sun Irish Summer Time
    - cron: '50 20 * * 1-5'   # 21:50 Mon–Fri Irish Summer Time
    # Winter (Irish time = UTC)
    - cron: '50 20 * * 6,0'   # 20:50 Sat/Sun Irish Standard Time
    - cron: '50 21 * * 1-5'   # 21:50 Mon–Fri Irish Standard Time
  workflow_dispatch:          # manual “Run workflow” button

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # Install Playwright + its browser dependencies
      - run: npm install playwright
      - run: npx playwright install --with-deps

      # Run the scraper and save a human-readable summary (for email body)
      - name: Run scraper
        run: node check.js | tee result.txt

      # ---------- PARSE the numbers once for later steps ----------
      - name: Parse counts
        id: nums
        run: |
          line1=$(grep '^PadelLK ' result.txt)
          line2=$(grep '^ProjectPadel ' result.txt)

          get_num () { echo "$1" | grep -oE "$2=[0-9]+(\.[0-9]+)?" | cut -d= -f2; }

          pkl_free=$(get_num "$line1" free)
          pkl_busy=$(get_num "$line1" busy)
          pkl_total=$(get_num "$line1" total)
          pkl_pct=$(get_num "$line1" pct)

          prj_free=$(get_num "$line2" free)
          prj_busy=$(get_num "$line2" busy)
          prj_total=$(get_num "$line2" total)
          prj_pct=$(get_num "$line2" pct)

          {
            echo "pkl_free=$pkl_free"
            echo "pkl_busy=$pkl_busy"
            echo "pkl_total=$pkl_total"
            echo "pkl_pct=$pkl_pct"
            echo "prj_free=$prj_free"
            echo "prj_busy=$prj_busy"
            echo "prj_total=$prj_total"
            echo "prj_pct=$prj_pct"
          } >> "$GITHUB_OUTPUT"

      # ---------- EMAIL: immediate nightly message ----------
      - name: Install msmtp (lightweight SMTP sender)
        run: sudo apt-get update -y && sudo apt-get install -y msmtp mailutils

      - name: Send nightly email
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          TO_EMAIL:  ${{ secrets.TO_EMAIL }}
        run: |
          cat > ~/.msmtprc <<EOF
          defaults
          auth           on
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt

          account default
          host $SMTP_HOST
          port 587
          from $SMTP_USER
          user $SMTP_USER
          password $SMTP_PASS
          EOF
          chmod 600 ~/.msmtprc

          SUBJECT="Padel occupancy $(date +%F)"
          cat > email_body.txt <<TXT
          PadelLK       free=${{ steps.nums.outputs.pkl_free }}  busy=${{ steps.nums.outputs.pkl_busy }}  total=${{ steps.nums.outputs.pkl_total }}  pct=${{ steps.nums.outputs.pkl_pct }}
          ProjectPadel  free=${{ steps.nums.outputs.prj_free }}  busy=${{ steps.nums.outputs.prj_busy }}  total=${{ steps.nums.outputs.prj_total }}  pct=${{ steps.nums.outputs.prj_pct }}
          TXT
          mail -s "$SUBJECT" "$TO_EMAIL" < email_body.txt

      # ---------- CSV ARCHIVE: append one row and commit ----------
      - name: Append to CSV log
        run: |
          mkdir -p data
          FILE=data/occupancy.csv
          if [ ! -f "$FILE" ]; then
            echo "date,padellk_free,padellk_busy,padellk_pct,projectpadel_free,projectpadel_busy,projectpadel_pct" > "$FILE"
