name: Padel-court occupancy

permissions:
  contents: write  # allow committing the CSV

on:
  schedule:
    # Summer (Irish time = UTC+1)
    - cron: '50 19 * * 6,0'   # 20:50 Sat/Sun Irish Summer Time
    - cron: '50 20 * * 1-5'   # 21:50 Mon–Fri Irish Summer Time
    # Winter (Irish time = UTC)
    - cron: '50 20 * * 6,0'   # 20:50 Sat/Sun Irish Standard Time
    - cron: '50 21 * * 1-5'   # 21:50 Mon–Fri Irish Standard Time
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # Install Playwright and browser (no --with-deps; not needed on ubuntu-latest)
      - run: npm install playwright@latest
      - run: npx playwright install chromium --quiet

      # Run the scraper (always produces two lines)
      - name: Run scraper
        run: node check.js | tee result.txt

      # Upload any debug screenshots (if scraper had to take them)
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screens
          path: debug-*.png
          if-no-files-found: ignore

      # ---------- PARSE the numbers once ----------
      - name: Parse counts
        id: nums
        shell: bash
        run: |
          set -e
          line1="$(grep '^PadelLK ' result.txt || true)"
          line2="$(grep '^ProjectPadel ' result.txt || true)"

          get_num () { echo "$1" | grep -oE "$2=[0-9]+(\.[0-9]+)?" | cut -d= -f2; }

          pkl_free="$(get_num "$line1" free)";   [ -n "$pkl_free"  ] || pkl_free=0
          pkl_busy="$(get_num "$line1" busy)";   [ -n "$pkl_busy"  ] || pkl_busy=0
          pkl_total="$(get_num "$line1" total)"; [ -n "$pkl_total" ] || pkl_total=0
          pkl_pct="$(get_num "$line1" pct)";     [ -n "$pkl_pct"   ] || pkl_pct=0.0

          prj_free="$(get_num "$line2" free)";   [ -n "$prj_free"  ] || prj_free=0
          prj_busy="$(get_num "$line2" busy)";   [ -n "$prj_busy"  ] || prj_busy=0
          prj_total="$(get_num "$line2" total)"; [ -n "$prj_total" ] || prj_total=0
          prj_pct="$(get_num "$line2" pct)";     [ -n "$prj_pct"   ] || prj_pct=0.0

          {
            echo "pkl_free=$pkl_free"
            echo "pkl_busy=$pkl_busy"
            echo "pkl_total=$pkl_total"
            echo "pkl_pct=$pkl_pct"
            echo "prj_free=$prj_free"
            echo "prj_busy=$prj_busy"
            echo "prj_total=$prj_total"
            echo "prj_pct=$prj_pct"
          } >> "$GITHUB_OUTPUT"

      # ---------- EMAIL via msmtp (Gmail App Password required) ----------
      - name: Install msmtp
        run: sudo apt-get update -y && sudo apt-get install -y msmtp

      - name: Send nightly email
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          TO_EMAIL:  ${{ secrets.TO_EMAIL }}
        run: |
          # Write msmtp config
          cat > ~/.msmtprc <<EOF
          defaults
          auth           on
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt

          account default
          host $SMTP_HOST
          port 587
          from $SMTP_USER
          user $SMTP_USER
          password $SMTP_PASS
          EOF
          chmod 600 ~/.msmtprc

          # Build the message and feed it directly to msmtp
          {
            echo "To: $TO_EMAIL"
            echo "From: $SMTP_USER"
            echo "Subject: Padel occupancy $(date +%F)"
            echo "Content-Type: text/plain; charset=UTF-8"
            echo
            echo "PadelLK
