name: Nightly Court Check

on:
  schedule:
    # 20:50 on Sat & Sun, 21:50 Mon-Fri
    - cron: "50 20 * * 6,0"
    - cron: "50 21 * * 1-5"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ✅ Official Playwright GitHub Action (no npm 429 errors)
      - name: Install Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Run scraper
        run: node check.js | tee result.txt

      - name: Parse counts
        id: parse
        run: |
          line1=$(grep '^PadelLK ' result.txt)
          line2=$(grep '^ProjectPadel ' result.txt)

          get_num () { echo "$1" | grep -oE "$2=[0-9]+(\.[0-9]+)?" | cut -d= -f2; }

          pkl_free=$(get_num "$line1" free)
          pkl_busy=$(get_num "$line1" busy)
          pkl_total=$(get_num "$line1" total)
          pkl_pct=$(get_num "$line1" pct)
          pkl_peak_busy=$(get_num "$line1" peak_busy)
          pkl_peak_total=$(get_num "$line1" peak_total)
          pkl_peak_pct=$(get_num "$line1" peak_pct)
          pkl_off_busy=$(get_num "$line1" off_busy)
          pkl_off_total=$(get_num "$line1" off_total)
          pkl_off_pct=$(get_num "$line1" off_pct)

          prj_free=$(get_num "$line2" free)
          prj_busy=$(get_num "$line2" busy)
          prj_total=$(get_num "$line2" total)
          prj_pct=$(get_num "$line2" pct)
          prj_peak_busy=$(get_num "$line2" peak_busy)
          prj_peak_total=$(get_num "$line2" peak_total)
          prj_peak_pct=$(get_num "$line2" peak_pct)
          prj_off_busy=$(get_num "$line2" off_busy)
          prj_off_total=$(get_num "$line2" off_total)
          prj_off_pct=$(get_num "$line2" off_pct)

          {
            echo "pkl_free=$pkl_free"
            echo "pkl_busy=$pkl_busy"
            echo "pkl_total=$pkl_total"
            echo "pkl_pct=$pkl_pct"
            echo "pkl_peak_busy=$pkl_peak_busy"
            echo "pkl_peak_total=$pkl_peak_total"
            echo "pkl_peak_pct=$pkl_peak_pct"
            echo "pkl_off_busy=$pkl_off_busy"
            echo "pkl_off_total=$pkl_off_total"
            echo "pkl_off_pct=$pkl_off_pct"

            echo "prj_free=$prj_free"
            echo "prj_busy=$prj_busy"
            echo "prj_total=$prj_total"
            echo "prj_pct=$prj_pct"
            echo "prj_peak_busy=$prj_peak_busy"
            echo "prj_peak_total=$prj_peak_total"
            echo "prj_peak_pct=$prj_peak_pct"
            echo "prj_off_busy=$prj_off_busy"
            echo "prj_off_total=$prj_off_total"
            echo "prj_off_pct=$prj_off_pct"
          } >> "$GITHUB_OUTPUT"

          # Append results to CSV
          d=$(date '+%Y-%m-%d %H:%M')
          echo "$d,$line1,$line2" >> results.csv

      - name: Commit results.csv
        uses: EndBug/add-and-commit@v9
        with:
          add: results.csv
          message: "Update results"

      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASS }}
          subject: "Padel Courts Occupancy Report"
          to: youremail@example.com
          from: Github Bot <bot@example.com>
          body: |
            ${{ env.line1 }}
            ${{ env.line2 }}

      # ✅ Always upload screenshots from check.js
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            snapshot-*.png
            debug-*.png
